-- Orbit Growth / Boostme Supabase migration
-- Paste this entire file into Supabase Dashboard > SQL Editor and run it once.
-- This schema keeps application users separate from auth.users because the app currently uses Manus OAuth.
-- The orbit-assets bucket is private. Uploads/downloads should go through your server using the Supabase service-role key.

create extension if not exists pgcrypto;

-- ---------- Enums ----------
do $$ begin
  create type public.user_role as enum ('user', 'admin');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.order_status as enum ('pending', 'in_progress', 'completed', 'canceled', 'partial', 'failed');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.wallet_transaction_type as enum ('deposit', 'order_charge', 'refund', 'adjustment');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.wallet_transaction_status as enum ('pending', 'completed', 'failed');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.sync_kind as enum ('catalog', 'orders');
exception when duplicate_object then null; end $$;
do $$ begin
  create type public.sync_status as enum ('running', 'completed', 'failed');
exception when duplicate_object then null; end $$;

-- ---------- Users and wallets ----------
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  open_id varchar(128) not null unique,
  name text,
  email varchar(320),
  login_method varchar(64),
  role public.user_role not null default 'user',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_signed_in timestamptz not null default now()
);

create table if not exists public.profiles (
  id bigint generated by default as identity primary key,
  user_id bigint not null unique references public.app_users(id) on delete cascade,
  email varchar(320),
  balance numeric(14,2) not null default 0 check (balance >= 0),
  api_key varchar(96) unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ---------- Provider catalog ----------
create table if not exists public.smm_providers (
  id bigint generated by default as identity primary key,
  name varchar(120) not null,
  api_url text not null,
  api_key text not null,
  is_active boolean not null default true,
  last_sync_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  provider_id bigint references public.smm_providers(id) on delete set null,
  provider_service_id varchar(80),
  name varchar(220) not null,
  platform varchar(40) not null,
  category varchar(80) not null,
  description text,
  wholesale_rate_per_1k numeric(12,4) not null default 0 check (wholesale_rate_per_1k >= 0),
  retail_rate_per_1k numeric(12,4) not null default 0 check (retail_rate_per_1k >= 0),
  min_quantity integer not null default 100 check (min_quantity > 0),
  max_quantity integer not null default 100000 check (max_quantity >= min_quantity),
  tags varchar(500),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);
create unique index if not exists services_provider_service_uidx on public.services(provider_id, provider_service_id) where provider_service_id is not null;
create index if not exists services_active_idx on public.services(is_active);

-- ---------- Orders ----------
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete restrict,
  service_id bigint not null references public.services(id) on delete restrict,
  provider_order_id varchar(120),
  target_link text not null,
  quantity integer not null check (quantity > 0),
  charge numeric(14,2) not null check (charge >= 0),
  start_count integer,
  remains integer,
  status public.order_status not null default 'pending',
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists orders_user_idx on public.orders(user_id);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_provider_idx on public.orders(provider_order_id) where provider_order_id is not null;

-- ---------- Wallet ledger ----------
create table if not exists public.wallet_transactions (
  id bigint generated by default as identity primary key,
  user_id bigint not null references public.app_users(id) on delete restrict,
  amount numeric(14,2) not null,
  type public.wallet_transaction_type not null,
  status public.wallet_transaction_status not null default 'completed',
  reference varchar(160) not null,
  payment_method varchar(80),
  balance_after numeric(14,2) not null check (balance_after >= 0),
  created_at timestamptz not null default now()
);
create index if not exists wallet_user_idx on public.wallet_transactions(user_id, created_at desc);
create unique index if not exists wallet_reference_uidx on public.wallet_transactions(user_id, reference);

-- ---------- Sync and audit ----------
create table if not exists public.sync_schedules (
  id bigint generated by default as identity primary key,
  kind public.sync_kind not null unique,
  task_uid varchar(65) not null unique,
  cron varchar(80) not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  provider_id bigint references public.smm_providers(id) on delete set null,
  kind public.sync_kind not null,
  status public.sync_status not null,
  items_processed integer not null default 0 check (items_processed >= 0),
  error_message text,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);
create index if not exists sync_runs_started_idx on public.sync_runs(started_at desc);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id bigint references public.app_users(id) on delete set null,
  action varchar(120) not null,
  entity_type varchar(80) not null,
  entity_id varchar(80),
  details jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_events_created_idx on public.audit_events(created_at desc);
create index if not exists audit_events_entity_idx on public.audit_events(entity_type, entity_id);

-- ---------- Supabase Storage metadata ----------
create table if not exists public.storage_files (
  id bigint generated by default as identity primary key,
  app_user_id bigint references public.app_users(id) on delete set null,
  bucket_id text not null default 'orbit-assets',
  object_path text not null,
  original_name text,
  mime_type text,
  byte_size bigint check (byte_size is null or byte_size >= 0),
  created_at timestamptz not null default now(),
  unique(bucket_id, object_path)
);
create index if not exists storage_files_user_idx on public.storage_files(app_user_id, created_at desc);

insert into storage.buckets (id, name, public)
values ('orbit-assets', 'orbit-assets', false)
on conflict (id) do update set public = excluded.public;

-- No client policies are intentionally created for storage.objects or storage_files.
-- Because the app uses Manus OAuth rather than Supabase Auth, browser-side auth.uid() cannot
-- identify an app user. Keep these objects private and access them from the server only.

-- ---------- updated_at trigger ----------
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists app_users_set_updated_at on public.app_users;
create trigger app_users_set_updated_at before update on public.app_users for each row execute function public.set_updated_at();
drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();

-- ---------- Row-level security ----------
alter table public.app_users enable row level security;
alter table public.profiles enable row level security;
alter table public.smm_providers enable row level security;
alter table public.services enable row level security;
alter table public.orders enable row level security;
alter table public.wallet_transactions enable row level security;
alter table public.sync_schedules enable row level security;
alter table public.sync_runs enable row level security;
alter table public.audit_events enable row level security;
alter table public.storage_files enable row level security;

-- The backend uses the Supabase service-role key, which bypasses RLS.
-- With no anon/authenticated policies, direct browser access is denied by default.

-- ---------- Optional helper for safe server-side wallet updates ----------
create or replace function public.apply_wallet_delta(p_user_id bigint, p_delta numeric)
returns numeric
language plpgsql
security definer
set search_path = public
as $$
declare
  v_balance numeric(14,2);
  v_next numeric(14,2);
begin
  select balance into v_balance from public.profiles where user_id = p_user_id for update;
  if not found then raise exception 'Wallet profile not found'; end if;
  v_next := round(v_balance + p_delta, 2);
  if v_next < 0 then raise exception 'Balance cannot become negative'; end if;
  update public.profiles set balance = v_next where user_id = p_user_id;
  return v_next;
end;
$$;
revoke all on function public.apply_wallet_delta(bigint, numeric) from public;

-- Verification queries. These return zero rows before the first import, which is expected.
select id, name, public from storage.buckets where id = 'orbit-assets';
select table_name from information_schema.tables where table_schema = 'public' and table_name in ('app_users','profiles','smm_providers','services','orders','wallet_transactions','sync_schedules','sync_runs','audit_events','storage_files') order by table_name;
