import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { ArrowRight, CalendarDays, CircleUserRound, CreditCard, LogOut, Mail, PackageCheck, ShieldCheck, Store } from "lucide-react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const formatDate = (value?: Date | string | null) => value ? new Date(value).toLocaleDateString(undefined, { year: "numeric", month: "long", day: "numeric" }) : "Not available";

export default function Account() {
  const { user, loading, logout } = useAuth();
  const [, setLocation] = useLocation();
  const initials = (user?.name || user?.email || "OG").split(/\s+/).map((part) => part[0]).slice(0, 2).join("").toUpperCase();
  const signOut = async () => { try { await logout(); setLocation("/"); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to sign out. Please try again."); } };

  return <DashboardLayout><div className="mx-auto min-w-0 max-w-5xl space-y-6">
    <header><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-cyan-200">Your account <span className="mx-1.5 text-slate-600">/</span> Details</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.045em] text-white sm:text-3xl">Account details</h1><p className="mt-2 text-sm leading-6 text-slate-400">Review the profile and sign-in information linked to this account.</p></header>
    {loading ? <div className="rounded-2xl border border-white/[.08] bg-[#0c131e] p-8 text-sm text-slate-400">Loading account details…</div> : user ? <>
      <section className="overflow-hidden rounded-2xl border border-blue-200/10 bg-[linear-gradient(135deg,rgba(35,75,133,.18),rgba(12,19,30,.95)_50%)]"><div className="flex flex-col gap-5 p-5 sm:flex-row sm:items-center sm:p-7"><Avatar className="h-16 w-16 border border-white/10"><AvatarFallback className="bg-blue-300/10 text-lg font-semibold text-blue-100">{initials}</AvatarFallback></Avatar><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="truncate text-xl font-semibold text-white">{user.name || "Your account"}</h2><span className="rounded-full border border-blue-200/10 bg-blue-200/[.05] px-2.5 py-1 text-[9px] font-medium uppercase tracking-wider text-blue-100">{user.role === "admin" ? "Administrator" : "Customer"}</span></div><p className="mt-1 truncate text-xs text-slate-400">{user.email}</p><p className="mt-3 inline-flex items-center gap-1.5 text-[10px] text-emerald-200"><span className="h-1.5 w-1.5 rounded-full bg-emerald-300" /> Signed in securely</p></div><Button variant="outline" className="h-9 self-start rounded-lg border-white/10 text-xs sm:self-center" onClick={signOut}><LogOut className="h-3.5 w-3.5" />Sign out</Button></div></section>
      <div className="grid gap-5 lg:grid-cols-[1.05fr_.95fr]">
        <section className="rounded-2xl border border-white/[.08] bg-[#0c131e] p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-300/[.07] text-blue-100"><CircleUserRound className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-white">Profile information</h2><p className="mt-1 text-[10px] text-slate-500">Details currently associated with your account</p></div></div><dl className="mt-5 divide-y divide-white/[.06]"><DetailRow icon={<CircleUserRound className="h-4 w-4" />} label="Full name" value={user.name || "Not provided"} /><DetailRow icon={<Mail className="h-4 w-4" />} label="Email address" value={user.email} /><DetailRow icon={<ShieldCheck className="h-4 w-4" />} label="Account type" value={user.role === "admin" ? "Administrator" : "Customer"} /><DetailRow icon={<CalendarDays className="h-4 w-4" />} label="Account created" value={formatDate(user.createdAt)} /></dl></section>
        <section className="rounded-2xl border border-white/[.08] bg-[#0c131e] p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-emerald-300/[.07] text-emerald-100"><ShieldCheck className="h-4 w-4" /></span><div><h2 className="text-sm font-semibold text-white">Sign-in & security</h2><p className="mt-1 text-[10px] text-slate-500">How access is currently managed</p></div></div><div className="mt-5 space-y-3"><div className="rounded-xl border border-white/[.06] bg-white/[.015] p-3.5"><p className="text-xs font-medium text-white">Password sign-in</p><p className="mt-1.5 text-[10px] leading-5 text-slate-400">Sign in with the email address and password you used to create this account. Password reset by email is not currently available.</p></div><div className="rounded-xl border border-white/[.06] bg-white/[.015] p-3.5"><p className="text-xs font-medium text-white">Session access</p><p className="mt-1.5 text-[10px] leading-5 text-slate-400">Your signed-in session is managed by the app using a protected HTTP-only cookie. Sign out on shared devices.</p></div><div className="rounded-xl border border-amber-200/10 bg-amber-200/[.025] p-3.5"><p className="text-xs font-medium text-amber-100">Email verification</p><p className="mt-1.5 text-[10px] leading-5 text-slate-400">Email verification is temporarily not required. Only register with an email address you control.</p></div></div></section>
      </div>
      <section className="rounded-2xl border border-white/[.08] bg-[#0c131e] p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-slate-500">Quick navigation</p><h2 className="mt-1.5 text-sm font-semibold text-white">Where would you like to go?</h2></div><div className="grid grid-cols-2 gap-2 sm:flex"><QuickLink icon={<Store className="h-3.5 w-3.5" />} label="Services" onClick={() => setLocation("/dashboard/services")} /><QuickLink icon={<PackageCheck className="h-3.5 w-3.5" />} label="Orders" onClick={() => setLocation("/dashboard/orders")} /><QuickLink icon={<CreditCard className="h-3.5 w-3.5" />} label="Wallet" onClick={() => setLocation("/dashboard/wallet")} /></div></div></section>
    </> : <div className="rounded-2xl border border-white/[.08] bg-[#0c131e] p-8 text-sm text-slate-400">Sign in to view account details.</div>}
  </div></DashboardLayout>;
}

function DetailRow({ icon, label, value }: { icon: React.ReactNode; label: string; value: string }) { return <div className="flex items-center gap-3 py-3.5"><span className="text-slate-500">{icon}</span><dt className="w-32 shrink-0 text-[10px] text-slate-500">{label}</dt><dd className="min-w-0 truncate text-xs font-medium text-slate-200">{value}</dd></div>; }
function QuickLink({ icon, label, onClick }: { icon: React.ReactNode; label: string; onClick: () => void }) { return <button onClick={onClick} className="inline-flex items-center justify-center gap-2 rounded-lg border border-white/[.08] px-3 py-2 text-[10px] font-medium text-slate-300 hover:border-white/20 hover:bg-white/[.04] hover:text-white">{icon}{label}<ArrowRight className="h-3 w-3" /></button>; }
