import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import ProviderMappingPanel from "@/components/ProviderMappingPanel";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { trpc } from "@/lib/trpc";
import { friendlyErrorMessage } from "@shared/errorMessages";
import { calculateServiceEconomics } from "@shared/finance";
import { calculateTieredRetailRatePer1k } from "@shared/pricing";
import { showErrorToast } from "@/lib/toasts";
import { Activity, AlertTriangle, ArrowRight, ArrowUpRight, Check, CircleDollarSign, Clock3, Database, Gauge, Loader2, Percent, Plus, RefreshCw, Search, Server, ShieldCheck, ShoppingBag, TrendingUp, Users, WalletCards, X } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const money = (value: unknown) => `KES ${Number(value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
const panel = "min-w-0 rounded-2xl border border-white/[.08] bg-[#0c131e] p-5 sm:p-6";
const fieldClass = "mt-2 h-10 rounded-lg border-white/10 bg-[#0a111b]";
type AdminTab = "overview" | "customers" | "orders" | "settings";

export default function Admin() {
  const { user, loading } = useAuth();
  const [, setLocation] = useLocation();
  const [activeTab, setActiveTab] = useState<AdminTab>("overview");
  useEffect(() => { if (!loading && (!user || user.role !== "admin")) setLocation("/dashboard"); }, [loading, user, setLocation]);

  const metrics = trpc.admin.metrics.useQuery(undefined, { enabled: activeTab === "overview" || activeTab === "settings" });
  const services = trpc.admin.services.useQuery(undefined, { enabled: activeTab === "settings" });
  const providers = trpc.admin.providers.useQuery(undefined, { enabled: activeTab === "settings" });
  const syncRuns = trpc.admin.syncRuns.useQuery(undefined, { enabled: activeTab === "settings" });
  const users = trpc.admin.users.useQuery(undefined, { enabled: activeTab === "customers" });
  const adminOrders = trpc.admin.orders.useQuery(undefined, { enabled: activeTab === "orders" });
  const walletActivity = trpc.admin.walletActivity.useQuery(undefined, { enabled: activeTab === "customers" });
  const [provider, setProvider] = useState({ id: undefined as number | undefined, name: "", apiUrl: "", apiKey: "" });
  const [service, setService] = useState({ name: "", platform: "Instagram", category: "Views", wholesaleRatePer1k: 12, retailRatePer1k: 30, minQuantity: 100, maxQuantity: 100000 });
  const [orderQuery, setOrderQuery] = useState("");
  const [orderStatus, setOrderStatus] = useState("all");
  const [orderPlatform, setOrderPlatform] = useState("all");

  const saveProvider = trpc.admin.saveProvider.useMutation({ onSuccess: () => { toast.success(provider.id ? "Provider updated" : "Provider saved"); setProvider({ id: undefined, name: "", apiUrl: "", apiKey: "" }); void providers.refetch(); }, onError: (error) => showErrorToast(error, "Provider could not be saved") });
  const removeProvider = trpc.admin.removeProvider.useMutation({ onSuccess: () => { toast.success("Provider removed"); void providers.refetch(); }, onError: (error) => showErrorToast(error, "Provider could not be removed") });
  const toggleProvider = trpc.admin.toggleProvider.useMutation({ onSuccess: (result) => { toast.success(result.isActive ? "Provider activated" : "Provider paused"); void providers.refetch(); }, onError: (error) => showErrorToast(error, "Provider status could not be changed") });
  const testProvider = trpc.admin.testProvider.useMutation({ onSuccess: (result) => toast.success("Connection healthy", { description: result.message }), onError: (error) => showErrorToast(error, "Connection test failed", "Check the provider details, then try again.") });
  const saveService = trpc.admin.upsertService.useMutation({ onSuccess: () => { toast.success("Service published"); void services.refetch(); }, onError: (error) => showErrorToast(error, "Service could not be published") });
  const runSync = trpc.admin.runSync.useMutation({ onSuccess: (result) => { toast.success(result.skipped ? "Sync skipped" : "Sync completed", { description: result.message }); void syncRuns.refetch(); void providers.refetch(); void services.refetch(); }, onError: (error) => showErrorToast(error, "Sync failed", "Check the provider settings and try again.") });
  const provisionSchedules = trpc.admin.provisionSyncSchedules.useMutation({ onSuccess: () => toast.success("Recurring syncs provisioned"), onError: (error) => showErrorToast(error, "Recurring sync could not be provisioned") });

  if (loading || !user || user.role !== "admin") return <div className="grid min-h-screen place-items-center bg-[#080d15] text-sm text-slate-400">Checking administrator access…</div>;
  const serviceEconomics = calculateServiceEconomics({ quantity: 1000, retailRatePer1k: service.retailRatePer1k, wholesaleRatePer1k: service.wholesaleRatePer1k });
  const allOrders = adminOrders.data ?? [];
  const orderRows = allOrders.filter((order) => {
    const needle = orderQuery.trim().toLowerCase();
    const matchesQuery = !needle || [order.serviceName, order.providerName, order.providerOrderId, order.customerName, order.customerEmail, String(order.id)].some((value) => String(value ?? "").toLowerCase().includes(needle));
    return matchesQuery && (orderStatus === "all" || order.status === orderStatus) && (orderPlatform === "all" || order.platform === orderPlatform);
  });
  const orderSummary = allOrders.reduce((summary, order) => ({ revenue: summary.revenue + Number(order.revenue ?? order.retailPaidKes ?? order.charge ?? 0), cost: summary.cost + Number(order.providerCost ?? order.wholesaleCostKes ?? 0), profit: summary.profit + Number(order.profit ?? order.netProfitKes ?? 0), losses: summary.losses + (order.isLoss ? 1 : 0) }), { revenue: 0, cost: 0, profit: 0, losses: 0 });
  const orderPlatforms = Array.from(new Set(allOrders.map((order) => order.platform).filter(Boolean))).sort();

  return <DashboardLayout><div className="mx-auto min-w-0 max-w-7xl space-y-6">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="inline-flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[.2em] text-violet-200"><ShieldCheck className="h-3.5 w-3.5" /> Administrator console</p><h1 className="mt-2 text-2xl font-semibold tracking-[-.045em] text-white sm:text-3xl">Operate with a clear view of the numbers.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Monitor revenue, customer activity, order progress, and platform health.</p></div><nav aria-label="Admin console sections" className="flex flex-wrap gap-2">{([["overview", "Overview"], ["customers", "Customers"], ["orders", "Orders"], ["settings", "Settings"]] as const).map(([tab, label]) => <button key={tab} type="button" aria-pressed={activeTab === tab} onClick={() => setActiveTab(tab)} className={`rounded-full border px-3 py-2 text-[10px] font-medium transition ${activeTab === tab ? "border-blue-200/20 bg-blue-200/[.08] text-blue-100" : "border-white/[.08] bg-white/[.025] text-slate-300 hover:border-white/20 hover:bg-white/[.06]"}`}>{label}</button>)}</nav></header>

    {activeTab === "overview" && <section id="overview" className="scroll-mt-24 space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Business overview</p><h2 className="mt-1 text-lg font-semibold text-white">Operating snapshot</h2></div><span className="text-[10px] text-slate-500">Live totals from recorded platform data</span></div>
      <QueryError label="Business overview" error={metrics.error} onRetry={() => void metrics.refetch()} />
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Metric label="Gross revenue" value={money(metrics.data?.grossRevenue)} note="Realized non-canceled sales" icon={<Gauge className="h-4 w-4" />} accent="blue" loading={metrics.isLoading || metrics.isError} /><Metric label="Provider cost" value={money(metrics.data?.providerCost)} note="Estimated wholesale cost" icon={<CircleDollarSign className="h-4 w-4" />} accent="amber" loading={metrics.isLoading || metrics.isError} /><Metric label="Net profit" value={money(metrics.data?.profit)} note={`After ${money(metrics.data?.refunds)} refunds`} icon={<TrendingUp className="h-4 w-4" />} accent="emerald" loading={metrics.isLoading || metrics.isError} /><Metric label="Profit margin" value={`${Number(metrics.data?.marginPercent ?? 0).toFixed(1)}%`} note="Profit ÷ gross revenue" icon={<Percent className="h-4 w-4" />} accent="cyan" loading={metrics.isLoading || metrics.isError} /><Metric label="Wallet liability" value={money(metrics.data?.walletLiability)} note="Customer balances on file" icon={<Database className="h-4 w-4" />} accent="violet" loading={metrics.isLoading || metrics.isError} /><Metric label="Customers" value={metrics.data?.users ?? 0} note={`${metrics.data?.activeServices ?? 0} active services`} icon={<Users className="h-4 w-4" />} accent="cyan" loading={metrics.isLoading || metrics.isError} /></div>

    </section>}

    {activeTab === "settings" && <section id="settings" className="scroll-mt-24 space-y-5"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-blue-200">Admin settings</p><h2 className="mt-1 text-lg font-semibold text-white">Manage providers and catalog.</h2></div>{Boolean(metrics.data?.failedSyncs) && <div className="flex items-center gap-2 rounded-xl border border-amber-200/15 bg-amber-200/[.05] px-4 py-3 text-xs text-amber-100"><AlertTriangle className="h-4 w-4 shrink-0" />{metrics.data?.failedSyncs} sync failure{metrics.data?.failedSyncs === 1 ? "" : "s"} to review in sync history.</div>}<QueryError label="Provider settings" error={providers.error} onRetry={() => void providers.refetch()} /><QueryError label="Service catalog" error={services.error} onRetry={() => void services.refetch()} /><ProviderMappingPanel providers={providers.data ?? []} /><div className="grid gap-5 xl:grid-cols-[1fr_.92fr]">
      <section className={panel}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-blue-200">Provider connections</p><h3 className="mt-1.5 text-base font-semibold text-white">Manage supply providers</h3><p className="mt-1 text-xs leading-5 text-slate-400">Credentials stay server-side. Test connectivity before syncing.</p></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-300/[.08] text-blue-200"><Server className="h-4 w-4" /></span></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2"><div><Label htmlFor="provider-name">Provider name</Label><Input id="provider-name" className={fieldClass} placeholder="Provider label" value={provider.name} onChange={(event) => setProvider({ ...provider, name: event.target.value })} /></div><div><Label htmlFor="provider-endpoint">API endpoint</Label><Input id="provider-endpoint" className={fieldClass} type="url" placeholder="https://provider.example/api/v2" value={provider.apiUrl} onChange={(event) => setProvider({ ...provider, apiUrl: event.target.value })} /></div><div className="sm:col-span-2"><Label htmlFor="provider-key">API key</Label><Input id="provider-key" className={fieldClass} type="password" autoComplete="new-password" placeholder={provider.id ? "Leave blank to keep existing key" : "Stored securely on the server"} value={provider.apiKey} onChange={(event) => setProvider({ ...provider, apiKey: event.target.value })} /></div></div>
        <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" disabled={saveProvider.isPending || !provider.name.trim() || !provider.apiUrl.trim() || (!provider.id && !provider.apiKey)} onClick={() => saveProvider.mutate({ ...provider, isActive: 1 })}>{saveProvider.isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <Plus className="h-3.5 w-3.5" />}{provider.id ? "Update provider" : "Save provider"}</Button><Button size="sm" variant="outline" disabled={runSync.isPending} onClick={() => runSync.mutate({ kind: "catalog" })}><RefreshCw className="h-3.5 w-3.5" />Sync catalog</Button><Button size="sm" variant="outline" disabled={runSync.isPending} onClick={() => runSync.mutate({ kind: "orders" })}><RefreshCw className="h-3.5 w-3.5" />Sync orders</Button><Button size="sm" variant="outline" disabled={provisionSchedules.isPending} onClick={() => provisionSchedules.mutate()}><Clock3 className="h-3.5 w-3.5" />Provision recurring</Button></div>
        <div className="mt-5 space-y-2">{(providers.data ?? []).map((item) => <div key={item.id} className="flex flex-col gap-3 rounded-xl border border-white/[.07] bg-white/[.015] p-3.5 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex items-center gap-2"><p className="truncate text-xs font-semibold text-white">{item.name}</p><span className={`rounded-full px-2 py-0.5 text-[9px] font-semibold uppercase tracking-wider ${item.isActive ? "bg-emerald-300/[.08] text-emerald-200" : "bg-white/[.06] text-slate-500"}`}>{item.isActive ? "Active" : "Paused"}</span></div><p className="mt-1 truncate text-[10px] text-slate-500">Credentials secured server-side · {item.lastSyncAt ? `Last sync ${new Date(item.lastSyncAt).toLocaleDateString()}` : "Not synced"}</p></div><div className="flex flex-wrap gap-1.5"><Button size="sm" variant="outline" className="h-7 px-2.5 text-[10px]" disabled={testProvider.isPending} onClick={() => testProvider.mutate({ id: item.id })}>{testProvider.isPending ? <Loader2 className="h-3 w-3 animate-spin" /> : "Test"}</Button><Button size="sm" variant="ghost" className="h-7 px-2.5 text-[10px]" onClick={() => setProvider({ id: item.id, name: item.name, apiUrl: item.apiUrl, apiKey: "" })}>Edit</Button><Button size="sm" variant="ghost" className="h-7 px-2.5 text-[10px]" disabled={toggleProvider.isPending} onClick={() => toggleProvider.mutate({ id: item.id, isActive: !Boolean(item.isActive) })}>{item.isActive ? "Pause" : "Activate"}</Button>{!item.isActive && <Button size="sm" variant="ghost" className="h-7 px-2.5 text-[10px] text-rose-200 hover:text-rose-100" disabled={removeProvider.isPending} onClick={() => removeProvider.mutate({ id: item.id })}>Remove</Button>}</div></div>)}{providers.data?.length === 0 && <EmptyState icon={<Server className="h-4 w-4" />} title="No providers connected" detail="Add a provider to bring services into your live catalog." />}</div>
      </section>

      <section id="catalog" className={`${panel} scroll-mt-24`}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-emerald-200">Retail catalog</p><h3 className="mt-1.5 text-base font-semibold text-white">Set the offer and protected price.</h3><p className="mt-1 text-xs leading-5 text-slate-400">Retail price is derived from wholesale: 2.5× through KES 20.00, then 1.4× above it.</p></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-emerald-300/[.08] text-emerald-200"><ShoppingBag className="h-4 w-4" /></span></div>
        <div className="mt-5 grid gap-3 sm:grid-cols-2"><div className="sm:col-span-2"><Label htmlFor="service-name">Service name</Label><Input id="service-name" className={fieldClass} placeholder="Describe the service clearly" value={service.name} onChange={(event) => setService({ ...service, name: event.target.value })} /></div><div><Label htmlFor="service-platform">Platform</Label><select id="service-platform" className="mt-2 h-10 w-full rounded-lg border border-white/10 bg-[#0a111b] px-3 text-xs text-white" value={service.platform} onChange={(event) => setService({ ...service, platform: event.target.value })}><option>Instagram</option><option>TikTok</option><option>YouTube</option></select></div><div><Label htmlFor="service-category">Category</Label><Input id="service-category" className={fieldClass} value={service.category} onChange={(event) => setService({ ...service, category: event.target.value })} /></div><div><Label htmlFor="service-cost">Wholesale / 1k</Label><Input id="service-cost" className={fieldClass} type="number" min={0} step="0.01" value={service.wholesaleRatePer1k} onChange={(event) => { const wholesaleRatePer1k = Number(event.target.value); setService({ ...service, wholesaleRatePer1k, retailRatePer1k: calculateTieredRetailRatePer1k(wholesaleRatePer1k) }); }} /></div><div><Label htmlFor="service-retail">Retail / 1k</Label><Input id="service-retail" className={fieldClass} type="number" readOnly value={service.retailRatePer1k} /></div><div><Label htmlFor="service-min">Minimum units</Label><Input id="service-min" className={fieldClass} type="number" min={1} value={service.minQuantity} onChange={(event) => setService({ ...service, minQuantity: Number(event.target.value) })} /></div><div><Label htmlFor="service-max">Maximum units</Label><Input id="service-max" className={fieldClass} type="number" min={1} value={service.maxQuantity} onChange={(event) => setService({ ...service, maxQuantity: Number(event.target.value) })} /></div></div>
        <div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-emerald-200/10 bg-emerald-300/[.035] p-3.5"><div><p className="text-[9px] font-medium uppercase tracking-[.14em] text-slate-500">Projected economics per 1,000</p><p className="mt-1 text-sm font-semibold text-emerald-100">{money(serviceEconomics.profit)} <span className="text-[10px] font-normal text-slate-400">profit · {money(serviceEconomics.revenue)} sale · {money(serviceEconomics.providerCost)} cost</span></p></div><p className="text-right text-[10px] text-slate-400">{serviceEconomics.marginPercent.toFixed(1)}% margin</p></div>
        <Button className="mt-4 w-full sm:w-auto" disabled={saveService.isPending || !service.name.trim() || service.wholesaleRatePer1k < 0 || service.retailRatePer1k < 0 || service.minQuantity < 1 || service.maxQuantity < service.minQuantity} onClick={() => saveService.mutate(service)}>{saveService.isPending ? <Loader2 className="h-4 w-4 animate-spin" /> : <Plus className="h-4 w-4" />}Publish service</Button>
        <div className="mt-6 border-t border-white/[.07] pt-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold text-white">Current catalog</p><span className="text-[10px] text-slate-500">{services.data?.length ?? 0} total</span></div><div className="max-h-64 space-y-2 overflow-y-auto pr-1">{services.data?.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 rounded-lg border border-white/[.05] bg-white/[.015] px-3 py-2.5"><div className="min-w-0"><p className="truncate text-xs font-medium text-white">{item.name}</p><p className="mt-1 truncate text-[10px] text-slate-500">{item.platform} · {item.category} · {money(item.retailRatePer1k)} / 1k</p></div><span className={`shrink-0 rounded-full px-2 py-1 text-[9px] ${item.isActive ? "bg-emerald-300/[.07] text-emerald-200" : "bg-white/[.05] text-slate-500"}`}>{item.isActive ? "Live" : "Hidden"}</span></div>)}{services.data?.length === 0 && <p className="py-4 text-center text-xs text-slate-500">Publish a service to make it available to customers.</p>}</div></div>
      </section>
    </div><section className={panel}><QueryError label="Sync history" error={syncRuns.error} onRetry={() => void syncRuns.refetch()} /><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-violet-200">Automation health</p><h3 className="mt-1.5 text-base font-semibold text-white">Sync history</h3></div><Activity className="h-4 w-4 text-violet-200" /></div><div className="mt-4 space-y-2">{(syncRuns.data ?? []).map((run) => <div key={run.id} className="flex items-center justify-between gap-3 rounded-xl border border-white/[.05] px-3.5 py-3"><div><p className="text-xs font-medium capitalize text-white">{run.kind} sync</p><p className="mt-1 text-[10px] text-slate-500">{new Date(run.startedAt).toLocaleString()}</p></div><span className={`inline-flex items-center gap-1.5 text-[10px] capitalize ${run.status === "completed" ? "text-emerald-200" : run.status === "failed" ? "text-rose-200" : "text-blue-200"}`}>{run.status === "failed" ? <AlertTriangle className="h-3 w-3" /> : <Clock3 className="h-3 w-3" />}{run.status}</span></div>)}{syncRuns.data?.length === 0 && <EmptyState icon={<Clock3 className="h-4 w-4" />} title="No sync runs recorded" detail="Sync events will appear here after the first run." />}</div><div className="mt-4 flex gap-2 border-t border-white/[.06] pt-4 text-[10px] leading-5 text-slate-500"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-emerald-200" />Run history is persisted, so failed and completed syncs remain visible.</div></section></section>}

    {activeTab === "customers" && <section id="customers" className="scroll-mt-24 min-w-0 space-y-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-slate-500">Customer operations</p><h2 className="mt-1 text-lg font-semibold text-white">Accounts and wallet activity</h2></div><QueryError label="Customer accounts" error={users.error} onRetry={() => void users.refetch()} /><QueryError label="Wallet activity" error={walletActivity.error} onRetry={() => void walletActivity.refetch()} /><div className="grid min-w-0 gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className={panel}><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-slate-500">Customer base</p><h3 className="mt-1.5 text-base font-semibold text-white">Recent accounts</h3></div><span className="grid h-9 w-9 place-items-center rounded-xl bg-blue-300/[.07] text-blue-100"><Users className="h-4 w-4" /></span></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[480px] text-left text-xs"><thead className="border-b border-white/[.07] text-[9px] uppercase tracking-[.13em] text-slate-500"><tr><th className="pb-3 font-semibold">Account</th><th className="pb-3 font-semibold">Role</th><th className="pb-3 font-semibold">Balance</th><th className="pb-3 font-semibold">Joined</th></tr></thead><tbody>{(users.data ?? []).slice(0, 12).map(({ user: customer, profile }) => <tr key={customer.id} className="border-b border-white/[.05] last:border-0"><td className="py-3.5"><p className="font-medium text-white">{customer.name || "Unnamed customer"}</p><p className="mt-1 text-[10px] text-slate-500">{customer.email}</p></td><td className="py-3.5 capitalize text-slate-400">{customer.role}</td><td className="py-3.5 tabular-nums text-slate-300">{money(profile?.balance)}</td><td className="py-3.5 whitespace-nowrap text-slate-500">{new Date(customer.createdAt).toLocaleDateString()}</td></tr>)}{users.data?.length === 0 && <tr><td colSpan={4} className="py-10 text-center text-slate-500">Customer accounts will appear here.</td></tr>}</tbody></table></div><p className="mt-3 text-[10px] leading-4 text-slate-500">Customer balances are liabilities; reconcile pending wallet requests before marking deposits as credited.</p></section>
      <section className={panel}><div className="flex items-center justify-between gap-3"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-emerald-200">Latest ledger entries</p><h3 className="mt-1.5 text-base font-semibold text-white">Wallet activity</h3></div><WalletCards className="h-4 w-4 text-emerald-200" /></div><div className="mt-4 space-y-2">{(walletActivity.data ?? []).slice(0, 8).map((tx) => <div key={tx.id} className="flex items-center justify-between gap-3 border-b border-white/[.05] py-2.5 last:border-0"><div className="min-w-0"><p className="text-xs font-medium text-white">Account #{tx.userId}</p><p className="mt-1 text-[10px] capitalize text-slate-500">{tx.type.replaceAll("_", " ")} · {tx.status}</p></div><span className={`shrink-0 text-xs font-medium tabular-nums ${Number(tx.amount) >= 0 ? "text-emerald-200" : "text-slate-200"}`}>{Number(tx.amount) >= 0 ? "+" : ""}{money(tx.amount)}</span></div>)}{walletActivity.data?.length === 0 && <EmptyState icon={<WalletCards className="h-4 w-4" />} title="No wallet entries yet" detail="New ledger activity will be shown here." />}</div></section>
    </div></section>}

    {activeTab === "orders" && <section id="operations" className="scroll-mt-24 space-y-5"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.18em] text-violet-200">Order operations</p><h2 className="mt-1 text-2xl font-semibold tracking-[-.04em] text-white">Provider-style fulfillment control.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Every order shows the provider job, customer charge, captured wholesale cost, and automatic realized profit. Historical orders keep the rates recorded at checkout.</p></div><Button size="sm" variant="outline" onClick={() => void adminOrders.refetch()} disabled={adminOrders.isFetching}><RefreshCw className={`mr-2 h-3.5 w-3.5 ${adminOrders.isFetching ? "animate-spin" : ""}`} />Refresh orders</Button></div><QueryError label="Customer orders" error={adminOrders.error} onRetry={() => void adminOrders.refetch()} />
      <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Captured revenue" value={money(orderSummary.revenue)} note={`${allOrders.length} orders loaded`} icon={<Gauge className="h-4 w-4" />} accent="blue" loading={adminOrders.isLoading} /><Metric label="Provider cost" value={money(orderSummary.cost)} note="Actual wholesale cost" icon={<CircleDollarSign className="h-4 w-4" />} accent="amber" loading={adminOrders.isLoading} /><Metric label="Realized profit" value={money(orderSummary.profit)} note="Revenue minus provider cost" icon={<TrendingUp className="h-4 w-4" />} accent="emerald" loading={adminOrders.isLoading} /><Metric label="Loss alerts" value={orderSummary.losses} note="Orders below provider cost" icon={<AlertTriangle className="h-4 w-4" />} accent="violet" loading={adminOrders.isLoading} /></div>
      <section className={panel}><div className="flex flex-col gap-3 xl:flex-row xl:items-center xl:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.16em] text-blue-200">Fulfillment queue</p><h3 className="mt-1.5 text-lg font-semibold text-white">All orders <span className="ml-1 text-sm font-normal text-slate-500">({orderRows.length} shown)</span></h3></div><div className="flex flex-col gap-2 sm:flex-row"><label className="relative block"><Search className="pointer-events-none absolute left-3 top-2.5 h-3.5 w-3.5 text-slate-500" /><Input aria-label="Search orders" className="h-9 w-full pl-9 text-xs sm:w-64" placeholder="Order, customer, service…" value={orderQuery} onChange={(event) => setOrderQuery(event.target.value)} />{orderQuery && <button type="button" aria-label="Clear search" className="absolute right-2 top-2 text-slate-500 hover:text-white" onClick={() => setOrderQuery("")}><X className="h-4 w-4" /></button>}</label><select aria-label="Filter order status" className="h-9 rounded-md border border-input bg-background px-3 text-xs text-foreground" value={orderStatus} onChange={(event) => setOrderStatus(event.target.value)}><option value="all">All statuses</option>{["pending", "in_progress", "completed", "partial", "failed", "canceled"].map((status) => <option key={status} value={status}>{status.replaceAll("_", " ")}</option>)}</select><select aria-label="Filter order platform" className="h-9 rounded-md border border-input bg-background px-3 text-xs text-foreground" value={orderPlatform} onChange={(event) => setOrderPlatform(event.target.value)}><option value="all">All platforms</option>{orderPlatforms.map((platform) => <option key={platform} value={platform}>{platform}</option>)}</select></div></div>
        <div className="mt-5 space-y-3">{orderRows.map((order) => <article key={order.id} className={`rounded-2xl border p-4 transition ${order.isLoss ? "border-rose-300/30 bg-rose-300/[.035]" : "border-white/[.07] bg-white/[.015] hover:border-blue-200/20"}`}><div className="flex flex-col gap-3 xl:flex-row xl:items-start xl:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold text-white">Order #{order.id}</span><OrderStatusBadge status={order.status} />{order.isLoss && <span className="rounded-full bg-rose-300/[.12] px-2.5 py-1 text-[9px] font-semibold uppercase tracking-wider text-rose-200">Loss blocked</span>}</div><p className="mt-1 truncate text-xs font-medium text-slate-200">{order.serviceName}</p><p className="mt-1 text-[10px] text-slate-500">{order.platform} · {order.quantity.toLocaleString()} units · customer {order.customerName} · {new Date(order.createdAt).toLocaleString()}</p></div><div className="flex flex-wrap items-center gap-2 text-[10px]"><span className="rounded-lg bg-white/[.05] px-2.5 py-2 text-slate-400">Provider <b className="ml-1 text-slate-200">{order.providerName}</b></span><span className="rounded-lg bg-white/[.05] px-2.5 py-2 text-slate-400">Job <b className="ml-1 font-mono text-slate-200">{order.providerOrderId ?? "Not submitted"}</b></span></div></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-5"><OrderStat label="Paid by customer" value={money(order.revenue ?? order.retailPaidKes ?? order.charge)} /><OrderStat label="Wholesale cost" value={money(order.providerCost ?? order.wholesaleCostKes)} /><OrderStat label="Profit" value={`${Number(order.profit ?? order.netProfitKes ?? 0) >= 0 ? "+" : "−"}${money(Math.abs(Number(order.profit ?? order.netProfitKes ?? 0)))}`} tone={Number(order.profit ?? order.netProfitKes ?? 0) >= 0 ? "profit" : "loss"} /><OrderStat label="Margin" value={`${Number(order.marginPercent ?? 0).toFixed(1)}%`} /><OrderStat label="Order link" value={order.targetLink} link /></div></article>)}{orderRows.length === 0 && <EmptyState icon={<ShoppingBag className="h-4 w-4" />} title={allOrders.length ? "No matching orders" : "No orders recorded"} detail={allOrders.length ? "Clear a filter or search a different order." : "New customer orders will enter the fulfillment queue here."} />}</div><p className="mt-4 text-[10px] leading-5 text-slate-500">Profit is calculated automatically from the order’s captured customer payment and provider wholesale cost. A red loss alert indicates a historical or blocked underpriced order that needs review.</p></section>
    </section>}
    {activeTab === "overview" && <footer className="flex flex-col gap-2 border-t border-white/[.06] pt-4 text-[10px] leading-5 text-slate-600 sm:flex-row sm:items-center sm:justify-between"><span>Gross order charges are not net profit. Review provider cost, wallet liability, and refunds before assessing realized margin.</span><a href="#overview" className="inline-flex items-center gap-1 font-medium text-slate-400 hover:text-white">Back to top <ArrowUpRight className="h-3 w-3" /></a></footer>}
  </div></DashboardLayout>;
}

function Metric({ label, value, note, icon, accent, loading }: { label: string; value: string | number; note: string; icon: React.ReactNode; accent: "blue" | "violet" | "emerald" | "cyan" | "amber"; loading: boolean }) {
  const colors = { blue: "border-blue-200/10 bg-blue-300/[.07] text-blue-100", violet: "border-violet-200/10 bg-violet-300/[.07] text-violet-100", emerald: "border-emerald-200/10 bg-emerald-300/[.07] text-emerald-100", cyan: "border-cyan-200/10 bg-cyan-300/[.07] text-cyan-100", amber: "border-amber-200/10 bg-amber-300/[.07] text-amber-100" };
  return <article className="rounded-2xl border border-white/[.08] bg-[#0c131e] p-4"><div className="flex items-start justify-between gap-2"><span className="text-[10px] font-medium leading-4 text-slate-400">{label}</span><span className={`grid h-8 w-8 shrink-0 place-items-center rounded-lg border ${colors[accent]}`}>{icon}</span></div><p className="mt-4 truncate text-lg font-semibold tracking-tight text-white tabular-nums">{loading ? "…" : value}</p><p className="mt-1 text-[9px] leading-4 text-slate-500">{note}</p></article>;
}
function OrderStat({ label, value, tone = "default", link = false }: { label: string; value: string; tone?: "default" | "profit" | "loss"; link?: boolean }) { const color = tone === "profit" ? "text-emerald-200" : tone === "loss" ? "text-rose-200" : "text-slate-200"; return <div className="min-w-0 rounded-xl border border-white/[.06] bg-black/[.12] px-3 py-2.5"><p className="text-[9px] uppercase tracking-[.12em] text-slate-500">{label}</p>{link ? <a href={value} target="_blank" rel="noreferrer" className="mt-1 block truncate text-[10px] text-blue-200 hover:text-white">Open target</a> : <p className={`mt-1 truncate text-sm font-semibold tabular-nums ${color}`}>{value}</p>}</div>; }
function EmptyState({ icon, title, detail }: { icon: React.ReactNode; title: string; detail: string }) { return <div className="rounded-xl border border-dashed border-white/[.08] px-4 py-7 text-center"><span className="mx-auto grid h-9 w-9 place-items-center rounded-lg bg-white/[.04] text-slate-400">{icon}</span><p className="mt-3 text-xs font-medium text-slate-300">{title}</p><p className="mt-1 text-[10px] leading-4 text-slate-500">{detail}</p></div>; }
function OrderStatusBadge({ status }: { status: string }) { const tone = status === "completed" ? "bg-emerald-300/[.10] text-emerald-200" : status === "failed" || status === "canceled" ? "bg-rose-300/[.10] text-rose-200" : status === "partial" ? "bg-amber-300/[.10] text-amber-200" : "bg-blue-300/[.10] text-blue-100"; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[9px] font-semibold capitalize ${tone}`}>{status.replaceAll("_", " ")}</span>; }

function QueryError({ label, error, onRetry }: { label: string; error: unknown; onRetry: () => void }) {
  if (!error) return null;
  return <div role="alert" className="flex flex-col items-start justify-between gap-3 rounded-xl border border-rose-300/15 bg-rose-300/[.035] px-4 py-3 sm:flex-row sm:items-center"><div><p className="text-xs font-medium text-rose-100">{label} couldn't be loaded</p><p className="mt-1 text-[10px] text-slate-400">{friendlyErrorMessage(error, "Check your connection and try again.")}</p></div><Button size="sm" variant="outline" className="h-8 shrink-0 border-rose-200/15 text-[10px]" onClick={onRetry}>Retry</Button></div>;
}
