import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Check, CloudDownload, Loader2, RefreshCw, SlidersHorizontal, Sparkles } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

type Provider = { id: number; name: string; isActive: number; lastSyncAt: Date | null };

export default function ProviderMappingPanel({ providers }: { providers: Provider[] }) {
  const [providerId, setProviderId] = useState("");
  const [markupPercent, setMarkupPercent] = useState(150);
  const [selected, setSelected] = useState<string[]>([]);
  const [query, setQuery] = useState("");
  const [syncFailures, setSyncFailures] = useState<Array<{ providerServiceId: string; error: string }>>([]);
  const catalog = trpc.admin.providerCatalog.useQuery({ providerId: Number(providerId) }, { enabled: Boolean(providerId), retry: false });
  const sync = trpc.admin.syncProviderServices.useMutation({
    onSuccess: (result) => { const failed = result.failures.length; setSyncFailures(result.failures); toast[failed ? "warning" : "success"](`${result.synced} services synced`, { description: failed ? `${failed} service${failed === 1 ? "" : "s"} failed. Review the details below and retry those selections.` : "Your local catalog is ready for client orders." }); void catalog.refetch(); setSelected([]); },
    onError: (error) => toast.error("Service sync failed", { description: error.message }),
  });
  const visible = useMemo(() => (catalog.data ?? []).filter((item) => `${item.service} ${item.name} ${item.category ?? ""}`.toLowerCase().includes(query.toLowerCase())), [catalog.data, query]);
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const selectAll = () => setSelected(selected.length === visible.length ? [] : visible.map((item) => item.providerServiceId));
  const activeProvider = providers.find((item) => item.id === Number(providerId));

  return <section className="rounded-2xl border border-blue-400/15 bg-gradient-to-br from-blue-500/[.07] via-white/[.025] to-transparent p-5 sm:p-6">
    <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div><div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[.18em] text-blue-300"><CloudDownload className="h-4 w-4" /> Provider mapping</div><h2 className="mt-2 text-xl font-semibold text-white">Bring your production catalog into orbit.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">Preview services without exposing provider credentials, choose exactly what to publish, and apply one consistent markup before syncing.</p></div><Badge variant="outline" className="w-fit border-blue-300/20 bg-blue-300/10 text-blue-200"><Sparkles className="mr-1.5 h-3.5 w-3.5" />Safe import flow</Badge></div>
    <div className="mt-6 grid gap-3 md:grid-cols-[1fr_160px_auto] md:items-end"><label className="text-sm text-slate-300"><span className="mb-2 block text-xs uppercase tracking-wider text-muted-foreground">Connected provider</span><select value={providerId} onChange={(event) => { setProviderId(event.target.value); setSelected([]); }} className="h-10 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground"><option value="">Choose a provider</option>{providers.filter((item) => item.isActive).map((provider) => <option key={provider.id} value={provider.id}>{provider.name}</option>)}</select></label><label className="text-sm text-slate-300"><span className="mb-2 block text-xs uppercase tracking-wider text-muted-foreground">Markup %</span><div className="relative"><SlidersHorizontal className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9" type="number" min={0} max={1000} value={markupPercent} onChange={(event) => setMarkupPercent(Number(event.target.value))} /></div></label><Button disabled={!providerId || catalog.isFetching} variant="outline" onClick={() => void catalog.refetch()}><RefreshCw className={`mr-2 h-4 w-4 ${catalog.isFetching ? "animate-spin" : ""}`} />Refresh catalog</Button></div>
    {activeProvider && <p className="mt-3 text-xs text-muted-foreground">{activeProvider.lastSyncAt ? `Last synced ${new Date(activeProvider.lastSyncAt).toLocaleString()}` : "Not synced yet"} · Provider credentials remain server-side.</p>}
    {!providerId && <div className="mt-6 rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-muted-foreground">Select an active provider to preview its live service catalog.</div>}
    {providerId && catalog.isLoading && <div className="mt-6 flex items-center justify-center rounded-xl border border-white/10 p-10 text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Loading production services…</div>}
    {providerId && catalog.error && <div className="mt-6 rounded-xl border border-red-400/20 bg-red-400/5 p-5 text-sm text-red-200">Unable to read this provider catalog. Check the endpoint, credentials, and provider API response.</div>}
    {syncFailures.length > 0 && <div className="mt-6 rounded-xl border border-amber-400/20 bg-amber-400/5 p-4 text-sm text-amber-100"><p className="font-medium">{syncFailures.length} service{syncFailures.length === 1 ? "" : "s"} need attention</p><div className="mt-2 space-y-1 text-xs text-amber-200/80">{syncFailures.map((failure) => <p key={failure.providerServiceId}><span className="font-medium">#{failure.providerServiceId}</span> — {failure.error}</p>)}</div></div>}
    {providerId && catalog.data && <><div className="mt-6 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><p className="text-sm font-medium text-white">{catalog.data.length} services available</p><Badge variant="secondary" className="bg-white/10 text-slate-300">{selected.length} selected</Badge></div><div className="flex gap-2"><Input className="h-9 w-52" placeholder="Filter services" value={query} onChange={(event) => setQuery(event.target.value)} /><Button size="sm" variant="ghost" onClick={selectAll}>{selected.length === visible.length ? "Clear visible" : "Select visible"}</Button></div></div><div className="mt-4 max-h-80 space-y-2 overflow-auto pr-1">{visible.map((item) => { const id = item.providerServiceId; const isSelected = selected.includes(id); const local = item.localService; const retail = Number(item.rate) * (1 + markupPercent / 100); return <button type="button" key={id} onClick={() => toggle(id)} className={`flex w-full items-center gap-3 rounded-xl border px-4 py-3 text-left transition ${isSelected ? "border-blue-400/40 bg-blue-400/10" : "border-white/8 bg-black/10 hover:border-white/15"}`}><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-md border ${isSelected ? "border-blue-300 bg-blue-400 text-white" : "border-white/20 text-transparent"}`}><Check className="h-3.5 w-3.5" /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-medium text-white">{item.name}</span><span className="mt-1 block truncate text-xs text-muted-foreground">#{id} · {item.category || item.type || "General"} · wholesale {Number(item.rate).toFixed(2)} / 1k</span></span><span className="hidden text-right sm:block"><span className="block text-xs text-muted-foreground">{local ? "Mapped" : "New mapping"}</span><span className="mt-1 block text-sm text-emerald-300">KES {retail.toFixed(2)} / 1k</span></span></button>; })}{visible.length === 0 && <p className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm text-muted-foreground">No provider services match this filter.</p>}</div><div className="mt-5 flex flex-col justify-between gap-3 border-t border-white/8 pt-5 sm:flex-row sm:items-center"><p className="text-xs leading-5 text-muted-foreground">Syncing updates existing mappings by provider service ID and keeps local availability enabled.</p><Button disabled={!selected.length || sync.isPending} onClick={() => sync.mutate({ providerId: Number(providerId), serviceIds: selected, markupPercent })}>{sync.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Sync {selected.length || "selected"} services</Button></div></>}
  </section>;
}
